### ISSUE TITLE
Using clamdscan with clamd running in docker

### ISSUE THREAD

**Issue by weisinc** [mko-x/docker-clamav#1]
I started clamd and freshclam in a docker container exposed over port 3310.
Is there a way to run clamdscan from a different host with this "dockerised" clamd daemon?

Thanks,
-Weisin

**Comment by mko-x** [comment]
Hi Weisin,

thank you for your Question. It is not yet possible out of the box. You need to modify the Dockerfile in order to do this. Remove the installation and startup of freshclam to have clamd on its own.

You could clone that repo and modify it.

If you need help feel free to ask me.

**Comment by groods-ehg** [comment]
@mko-x would like to deploy clam in a container in AWS ECS (Elastic Container Service) and replicate the same pattern for x (> 500) dedicated hosts running docker locally. Can you please offer a pattern where x other containers can call clamdscan from a central clam based container. The cludgy method after a couple of hours of research is via socket either via common volume mount (really bad) or via private docker network (much better) but need to know how to stitch it together i.e. what to expose from the clam container and how to consume the clamdscan service from other containers.

Any assistance in this matter would be greatly appreciated. Orchestration will be varied between AWS taskDefs for ECS clusters and compose for on-prem so don't require details for orchestration just best practices and methods for exposing and consuming clamdscan from other containers.

Will raise this in a new general post as this thread is closed but am hoping you notice this and can respond.

Kind regards
Greg
