### ISSUE TITLE
Can't run docker-clamav in Azure container instance

### ISSUE THREAD

**Issue by kshke** [mko-x/docker-clamav#101]
Hello Team,

when i use following command to create ACI， it usually be killed. could you please help to check?

az container create --resource-group aci --name large-file-virus-scanner --image mkodockx/docker-clamav:latest --ports 3310 --ip-address Public --restart-policy OnFailure

From the logs in container, it can’t download daily-25972.cdiff from https://database.clamav.net/daily-25972.cdiff

So I try to access the website in my computer, it shows “404 not found”. 

ue Feb  9 05:38:57 2021 -> ClamAV update process started at Tue Feb  9 05:38:57 2021
Tue Feb  9 05:38:57 2021 -> daily database available for update (local version: 25970, remote version: 26074)
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
Tue Feb  9 05:39:25 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:25 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:25 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:25 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:25 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:25 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:25 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:25 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:26 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:26 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 05:39:26 2021 -> ^Incremental update failed, trying to download daily.cvd
Tue Feb  9 05:39:42 2021 -> Testing database: '/var/lib/clamav/tmp.f6bfc/clamav-f5866aab3ef937dea55fb1d741f6a3a9.tmp-daily.cvd' ...

**Comment by kshke** [comment]
Run this in unbuntu, got same error.

root@ubuntu1:~#  docker run -d -p 3310:3310 mkodockx/docker-clamav:latest
Unable to find image 'mkodockx/docker-clamav:latest' locally
latest: Pulling from mkodockx/docker-clamav
bb79b6b2107f: Pull complete
0ee80008aa06: Pull complete
e7be1c742cc0: Pull complete
94c4f74aa598: Pull complete
16497318fc29: Pull complete
9a5df4081fd7: Pull complete
b45a49f86771: Pull complete
e3ffad146795: Pull complete
b58400aa232e: Pull complete
Digest: sha256:a08979a3e33794616c65abd037c834184065f4933e11453d23d020f0f1e17d33
Status: Downloaded newer image for mkodockx/docker-clamav:latest
e0b0eed62b2ddcd889fc359613ef4f4f38afa9c78033a713832b73325d4cbbb7

root@ubuntu1:~# docker logs e0b0eed62b2d
Tue Feb  9 04:03:59 2021 -> ClamAV update process started at Tue Feb  9 04:03:59 2021
Tue Feb  9 04:03:59 2021 -> daily database available for update (local version: 25970, remote version: 26074)
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************
Tue Feb  9 04:04:02 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 04:04:02 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdif                                  f
Tue Feb  9 04:04:02 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 04:04:02 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdif                                  f
Tue Feb  9 04:04:02 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 04:04:02 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdif                                  f
Tue Feb  9 04:04:02 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 04:04:02 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdif                                  f
Tue Feb  9 04:04:02 2021 -> ^downloadFile: file not found: https://database.clamav.net/daily-25971.cdiff
Tue Feb  9 04:04:02 2021 -> ^getpatch: Can't download daily-25971.cdiff from https://database.clamav.net/daily-25971.cdif                                  f
Tue Feb  9 04:04:02 2021 -> ^Incremental update failed, trying to download daily.cvd
Tue Feb  9 04:04:08 2021 -> Testing database: '/var/lib/clamav/tmp.2f59a/clamav-b8beeeb004d85df409641b91a49c044a.tmp-dail

**Comment by eberdev** [comment]
I too would love it if this can be addressed.  It seems it's trying to incrementally download a daily which does not exist, then attempts to test: > Testing database: '/var/lib/clamav/tmp.9b60f/clamav-81c81e383654954ede072e65e05a2ce3.tmp-daily.cvd' 

then for me at least it shows 
/bootstrap.sh: line 35:    14 Killed                  freshclam -d

if i try this in azure containers with :alpine the system doesn't even get this far.

**Comment by mko-x** [comment]
I have not digged into Azure yet. So I cannot reproduce or investigate anything. If

What I can state: Sometimes over any OS and configurations, clam has problems downloading the daily database updates. That might be related to updating download mirrors etc.

You need to ensure proxy, dns and other network configuration are correct. Maybe you can set extra parameters to CLI

**Comment by mko-x** [comment]
Follow up in #103 .
