### ISSUE TITLE
Not able to mount custom configuration (clamd.conf) into the docker

### ISSUE THREAD

**Issue by rishinith** [mko-x/docker-clamav#104]
I want to add my custom configuration for ClamAV. I followed the documentation and now using this command to start the docker.
`sudo docker run -v /etc/clamd.d/:/mnt/ -e CLAMD_CONF_FILE=/mnt/clamd.conf -p 3310:3310 mkodockx/docker-clamav  
`
**Host configuration path:** /etc/clamd.d/clamd.conf
**Docker configuration path:** /mnt/clamd.conf **[ I can see this on docker]**
The environment variable `CLAMD_CONF_FILE `is correct on docker i.e `/mnt/clamd.conf`

But this configuration is not being copied in clamav
_The file ` /etc/clamav/clamd.conf ` is still containing the old configuration_

Let me know what's the problem here.

Thanks

**Comment by mko-x** [comment]
Is the docker daemon allowed to access the file? Did you check permissions oft /etc/clam.d/.. ?

**Comment by mko-x** [comment]
You may explain what fixed your error to help other users (:

**Comment by rishinith** [comment]
Sorry for the late reply.
Actually, I was using the latest image.
Docker pull resolved the issue.
Thanks
