### ISSUE TITLE
installation help

### ISSUE THREAD

**Issue by ramkumarmurugudu** [mko-x/docker-clamav#105]
can any one help me on the installation on rhel8

**Comment by mko-x** [comment]
Describe your issue please. What are you doing on what kind of machine? Did you install Docker, where are you stuck?

**Comment by ramkumarmurugudu** [comment]
How to enable https for clamav-api

**Comment by mko-x** [comment]
Use a proxy like https://github.com/solita/clamav-rest and make it available via ssl.
