### ISSUE TITLE
bootstrap.sh - Handle custom database directory

### ISSUE THREAD

**Issue by DavidJFowler** [mko-x/docker-clamav#107]
**Describe the bug**
[bootstrap.sh](https://github.com/mko-x/docker-clamav/blob/master/alpine/edge/bootstrap.sh) does not handle the initial clam DB download correctly if the database directory has been set to a value other than ` /var/lib/clamav`

**To Reproduce**
Use custom config files.
In your custom freshclam.conf and clamd.conf files set `DatabaseDirectory` to a custom directory (e.g. in a mounted volume)

**Expected behavior**
The initial DB download checks for the existence of `main.cvd` in the custom database directory.

**Actual behavior**
The initial DB download always checks for the existence of `main.cvd` in `/var/lib/clamav`

I suggest the following change be made to bootstrap.sh.

Replace
```shell
MAIN_FILE="/var/lib/clamav/main.cvd"

if [ ! -f ${MAIN_FILE} ]; then
    echo "[bootstrap] Initial clam DB download."
    /usr/bin/freshclam
fi
```
with
```shell
DB_DIR=$(sed -n 's/^DatabaseDirectory\s\(.*\)\s*$/\1/p' /etc/clamav/freshclam.conf )
DB_DIR=${DB_DIR:-'/var/lib/clamav'}
MAIN_FILE="$DB_DIR/main.cvd"
echo "[bootstrap] Checking for Clam DB in $MAIN_FILE"

if [ ! -f ${MAIN_FILE} ]; then
    echo "[bootstrap] Initial clam DB download."
    /usr/bin/freshclam
fi
```

**Comment by mko-x** [comment]
Thank you @DavidJFowler ! You have the fix already here, would you mind creating a PR for the images? The solution looks very good to me 🦸 👍

**Comment by DavidJFowler** [comment]
@mko-x Pull request: https://github.com/mko-x/docker-clamav/pull/109
