### ISSUE TITLE
Don't know how to get started in nodejs with dockerized clamAV

### ISSUE THREAD

**Issue by tomeczekstecc** [mko-x/docker-clamav#111]
**I can't get started with dockerized clamav app**

I know it is not a bug, but overviewed docs, googled dozen times and still get the same output.

I built  a nodejs app  with a muter-based upload. There is a function that takes uploded file path and gets NodeClam() instance to work:

```javascript
import NodeClam from 'clamscan'

// clamscan module configs
const ClamScan = new NodeClam().init({
    clamdscan: {
        socket: '/var/run/clamav/clamd.sock',
        host: '127.0.0.1',
        port: 3310,
    }
});

// Scan file using clamscan module
export function scanFile(filePath) {
  return ClamScan.then(async clamscan => {
    const { is_infected, viruses } = await clamscan.scan_file(filePath);


    if (is_infected) {
      console.log(`The file is INFECTED with ${viruses}`);
      throw new Error('ERR_FILE_SCAN_INFECTED');
    } else {

      return 'CLEAN';
    }
  }).catch(err => {
    console.log(err)
    throw new Error(err);
  });
}

```

**And than I get this output in node console (printing an error):**
```bash
[server] Error: connect ENOENT /var/run/clamav/clamd.sock
[server]     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16) {
[server]   errno: -4058,
[server]   code: 'ENOENT',
[server]   syscall: 'connect',
[server]   address: '/var/run/clamav/clamd.sock'
[server] }
[server] (node:24904) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
[server] (Use `node --trace-warnings ...` to show where the warning was created)
```
I checked for directory in  docker (via bash) and a file directory seems to be fine:

```bash
/run/clamav $ ls -la
total 20
drwxr-x---    1 clamav   clamav        4096 Apr  3 19:16 .
drwxr-xr-x    1 root     root          4096 Feb 24 16:02 ..
-rw-rw-r--    1 clamav   clamav           2 Apr  3 19:16 clamd.pid
srw-rw-rw-    1 clamav   clamav           0 Apr  3 19:16 clamd.sock
-rw-rw----    1 clamav   clamav           3 Apr  3 19:16 freshclam.pid
/run/clamav $ pwd
/var/run/clamav
```

**Host:**
 - OS: windows/WSL
 - Version 10

**Image:**
 - Tag: mkodockx/docker-clamav:alpine
 - Configuration:
 
```yml
  clamAV:
    image:  mkodockx/docker-clamav:alpine
    restart: always
    ports:
      - 3310:3310
    volumes:
      - ./data/clamav:/var/lib/clamav
```

What am I missing to do?

**Comment by tomeczekstecc** [comment]
On ubuntu (18.04 on Digital Ocean's Drroplet) the case is very similar
```shell
0|stypendia-server  | Error: Error: connect ENOENT /var/run/clamav/clamd.sock
0|stypendia-server  |     at /home/tomek/apps/stypendia/src/services/scanFile.ts:24:11
0|stypendia-server  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|stypendia-server  | (node:17072) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
0|stypendia-server  | (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by mko-x** [comment]
Hey @tomeczekstecc,
thank you for your question.

Well, did you try
`Use `node --trace-warnings ...` to show where the warning was created` ?

And: Please read the docs. For your used module here: https://www.npmjs.com/package/clamscan

> As of version v1.0.0, this module supports communication with a local or remote ClamAV daemon through Unix Domain sockets or a TCP host/port combo. If you supply both in your configuration object, the UNIX Domain socket option will be used. 

Remove the socket path from the configuration and try again.

You could use a self created socket file as well, but not both - sockets and ip-config.

**Comment by tomeczekstecc** [comment]
Couldn't print ```--trace-warnings``` since I use TS in background... but removing a socket path did the trick. I'm very 
grateful for Your help.
And thanks for Your work!!! I appreciate that.

**Comment by mko-x** [comment]
Ah I see :D Great that it works for you now as well!

**Comment by Tommy1223454** [comment]
The root cause here is that clamscan prioritizes the socket path over TCP
when both are provided — so even if your TCP config is correct, the socket
wins and fails because the container socket isn't mounted into your host.

The cleanest fix for Docker is to drop the socket config entirely and use
TCP only. That said, if you're still fighting the clamscan API, you might
want a wrapper that makes the Docker TCP path the default first-class option.

I built `pompelmi` to make exactly this use case zero-config:
```
  import { scan } from 'pompelmi';

  const result = await scan(req.file.path, {
    host: '127.0.0.1',  // your Docker container
    port: 3310
  });
  // 'Clean' | 'Malicious' | 'ScanError'
```


No socket paths, no binary lookups, no daemon on your host machine.
Works directly with mkodockx/docker-clamav and the official clamav/clamav image.
https://www.npmjs.com/package/pompelmi
