### ISSUE TITLE
Build Action Error

### ISSUE THREAD

**Issue by mko-x** [mko-x/docker-clamav#115]
```bash
Error: Unable to process command '::set-env name=DOTNET_ROOT::../share/dotnet' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Error: Unable to process command '::add-path::/opt/hostedtoolcache/GitVersion.Tool/5.6.8/x64' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Maybe we should change to env

**Comment by mko-x** [comment]
After updating GitTools it works! Thanks to @WhiteBahamut !!


Auto versioned releases.

https://hub.docker.com/layers/mkodockx/docker-clamav/1.0.0-ci.176-alpine-edge/images/sha256-280d3ad19ccd173feac46ff96ff8e7594ef6741410f2eff1709e86cc6dcb6431?context=repo

Some Errors still for debian builds. Will look at it.

**Comment by mko-x** [comment]
Hahaha - debian builds fail due to `wget`errors during downloads of the databases 👯 

```bash
Dockerfile:23
--------------------
  22 |     # initial update of av databases
  23 | >>> RUN wget -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd && \
  24 | >>>     wget -O /var/lib/clamav/daily.cvd http://database.clamav.net/daily.cvd && \
  25 | >>>     wget -O /var/lib/clamav/bytecode.cvd http://database.clamav.net/bytecode.cvd && \
  26 | >>>     chown clamav:clamav /var/lib/clamav/*.cvd
  27 |     
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c wget -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd &&     wget -O /var/lib/clamav/daily.cvd http://database.clamav.net/daily.cvd &&     wget -O /var/lib/clamav/bytecode.cvd http://database.clamav.net/bytecode.cvd &&     chown clamav:clamav /var/lib/clamav/*.cvd]: exit code: 8
Error: buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c wget -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd &&     wget -O /var/lib/clamav/daily.cvd http://database.clamav.net/daily.cvd &&     wget -O /var/lib/clamav/bytecode.cvd http://database.clamav.net/bytecode.cvd &&     chown clamav:clamav /var/lib/clamav/*.cvd]: exit code: 8
```

**Comment by WhiteBahamut** [comment]
Also looks it should be a different version var. `steps.gitversion.outputs.semVer` -> `steps.gitversion.outputs.MajorMinorPatch`. Missed that one :( Maybe the inital update should be moved to the first start anyways. So the images get smaller ;-)

**Comment by mko-x** [comment]
Removed the db initialisation and it works.

But for some reason it creates 5 build jobs:

<img width="177" alt="grafik" src="https://user-images.githubusercontent.com/10264942/115126383-dfb20f80-9fce-11eb-9afc-91bf1d6dafdc.png">

**Comment by WhiteBahamut** [comment]
haha yeha, there is a typo :(
![image](https://user-images.githubusercontent.com/38832027/115126446-5d761b00-9fcf-11eb-9a36-375ba55b7303.png)

**Comment by mko-x** [comment]
Ahh, got ya :D  Thankx ;D

**Comment by WhiteBahamut** [comment]
Is the action running automatic? You should keep an eye on the version number... in theory a commit should increase the path number automatically. Not sure if I have configure it right ;-) Right now it seems it is not counting correct

**Comment by mko-x** [comment]
Yes, it is running on push. Should stay at MajorMinorPatch from the GitVersion file I guess

**Comment by mko-x** [comment]
All builds pass.
