### ISSUE TITLE
Docker --link deprecation

### ISSUE THREAD

**Issue by Denperidge** [mko-x/docker-clamav#118]
The README suggests a very convenient way of linking container using run --link. However, Docker has warned that [it has become a legacy feature and may eventually even be removed](https://docs.docker.com/network/links/). As far as I'm aware, the replacement is their [network](https://docs.docker.com/network/) system, although I'm not 100% certain. It may not be bad to replace that part of the README down the line!

**Comment by mko-x** [comment]
Thank you for your hint! 👍🏼 

Would you mind creating a PR for the Readme with a new explanation for the network configuration?

**Comment by Denperidge** [comment]
I'm sadly not too experienced with the new system either, but I'll try to make a PR soon with links to the documentation in case of issues and so that I'm suggesting Docker-sanctioned configuration!

**Comment by mko-x** [comment]
Thank you very much! Appreciating your help 👍🏼  😸
