### ISSUE TITLE
Why are there 2 different docker image sources?

### ISSUE THREAD

**Issue by PAX523** [mko-x/docker-clamav#119]
Question: There are two different docker image sources. What's the reason for having 2 sources for this image? Which one is obsolete and which one actively maintained? Which one is recommended to be used?

* https://hub.docker.com/r/mk0x/docker-clamav
* https://hub.docker.com/r/mkodockx/docker-clamav

**Comment by mko-x** [comment]
Good question. Well some time ago I wasn't able to access the original source account for mkodockx. To be able to publish anything, I created the mk0x account. After several mails and chats and a lot of time I was able to reset the original account. I will close the mk0x one or mark it as deprecated.
