### ISSUE TITLE
Unable to connect to clamd

### ISSUE THREAD

**Issue by ldm810** [mko-x/docker-clamav#12]
I am using the latest docker image pushed to docker hub  running with the command 
```
docker run -d -p 3310:3310 mkodockx/docker-clamav
```

```
^Clamd was NOT notified: Can't connect to clamd through /var/run/clamav/clamd.ctl: No such file or directory
```

I ran `ps -ef | grep clamd` but I see that `clamav` is running. I see the following:
```
ps -ef | grep clamd
```

Is this something to be concerned about?

**Comment by mko-x** [comment]
What is the output of 
`ps`
inside the container ?

**Comment by ldm810** [comment]
I can send the PING and am able to use the service. Here is the output of ps -a

  PID TTY          TIME CMD
   19 pts/0    00:00:00 ps

**Comment by ldm810** [comment]
@mko-x kindly following up on this. Is there anything else I can provide?

**Comment by wwwindisch** [comment]
Sorry for commenting on this closed issue, but I experience exactly the same problem:
I get 

> ^Clamd was NOT notified: Can't connect to clamd through /var/run/clamav/clamd.ctl: No such file or directory
The container is marked as "unhealthy", but nevertheless clamav it seems to be working.

_ps -a_ gives:
```
PID   USER     TIME  COMMAND
    1 root      0:00 {bootstrap.py} /usr/bin/python3 /bootstrap.py
   30 root      0:00 freshclam -d -c 6
   31 root      1:36 clamd
  265 root      0:00 bash
  275 root      0:00 ps -a
```

and _ls -l /tmp/clamd.sock_ gives:

`srw-rw-rw-    1 root     root             0 Nov 13 00:09 /tmp/clamd.sock`

The corresponding entry in my docker-compose yml:

```
av:
    image: mk0x/docker-clamav:alpine
    container_name: nextav
    restart: always
    networks:
      - datanet0
    volumes:
      - "./config_volumes/clamav:/etc/clamav"
```
I'm looking forward to your feedback on how to fix this issue.
Kind regards,
Markus
