### ISSUE TITLE
ENV variables for alpine image

### ISSUE THREAD

**Issue by dmytrohridin** [mko-x/docker-clamav#122]
Debian version of clamav have the possibility to run with custom --env argument CLAMD_CONF_... while alpine does not use this behavior, only mounting custom file?
Is this expected behavior?
Thank you

**Comment by igilabert** [comment]
I'm also having this issue. Is there any plan to allow setting env variables for alpine image?

**Comment by mko-x** [comment]
This feature is not yet implemented for alpine version as most use-cases can be realised with custom configuration file. 
Do you need this feature explicitly? 
Could you or anyone provide a PR?
I could dig in but I need to find a time slot for the changes and tests. It should be pretty easy as the functionality is already available in the debian image.

**Comment by mko-x** [comment]
Fixed by #127

**Comment by dmytrohridin** [comment]
@mko-x does it make sense to add this envconfig for https://github.com/mko-x/docker-clamav/tree/master/alpine/main-idb too?

**Comment by mko-x** [comment]
Ahoi @dmytrohridin,

yes that makes sense. Envconfig will be automatically available with the next built of the idb image as it is based on the alpine image.
