### ISSUE TITLE
Can't run the images.

### ISSUE THREAD

**Issue by Tom284** [mko-x/docker-clamav#123]
Whatever I pull or build the images, Clamav somehow always get stuck when it is downloading it's files.

```
Time: 3.6s, ETA: 5.3s [=========> ] 41.15MiB/101.48MiB

Time: 3.6s, ETA: 5.2s [=========> ] 41.65MiB/101.48MiB

Time: 3.7s, ETA: 5.2s [=========> ] 42.11MiB/101.48MiB

Time: 3.7s, ETA: 5.1s [=========> ] 42.51MiB/101.48MiB
```
(After the final one nothing happens anymore.)

I have tried it with the Alpine and the Alpine-edge files. I have also tried it on 2 separate pc's. 
I am using Docker desktop.

EDIT:

When I build the image myself it still doesn't work and when I use docker pull `mkodockx/docker-clamav:alpine` it also doesn't work. But when I use 
`docker run --health-cmd=./check.sh --health-start-period=120s --health-interval=60s --health-retries=3 -p 3310:3310 mkodockx/docker-clamav:alpine` it does work. I need to be able to build the Dockerfile and image myself though. So the issue sadly isn't resolved yet.

**Comment by mko-x** [comment]
Hey @Tom284 ,

this problem is caused by Cloudflare protection of ClamAV database servers. See #103 for more information. You may try the preloaded database image.
