### ISSUE TITLE
alpine-idb-amd64 image out-of-date

### ISSUE THREAD

**Issue by eht16** [mko-x/docker-clamav#128]
The `alpine-idb-amd64` image on Docker Hub is outdated.

I assume this is because it is not built automatically because it needs manual download of the database files?

@mko-x, would you mind to update it manually from time to time?

**Comment by mko-x** [comment]
Ahoi @eht16,
you're right. The image has to be built on my machine at the moment as github doesn't allow files > 100 MB and automation would be killed by the Cloudflare protection.

I will update the image manually from time to time on my own schedule or if requested explicitly here by the community. Just like you did.

I'm creating a new image version right now and will provide more information soon here and within the code repo.

**Comment by mko-x** [comment]
Push was successful.

Latest tag is now: **mkodockx/docker-clamav:alpine-idb-amd64-v2021-05-25**

The build tag now additionally includes the date of database file downloading to allow sticking to a special version.

**Comment by mko-x** [comment]
See

https://hub.docker.com/layers/mkodockx/docker-clamav/alpine-idb-amd64-v2021-05-25/images/sha256-89dcc6a66443c10de4716e756aafd33d72d78f12ff608599ffec5e90a6249980?context=repo

**Comment by eht16** [comment]
> Ahoi @eht16,
> you're right. The image has to be built on my machine at the moment as github doesn't allow files > 100 MB and automation would be killed by the Cloudflare protection.
> 
> I will update the image manually from time to time on my own schedule or if requested explicitly here by the community. Just like you did.

Fair enough.

> I'm creating a new image version right now and will provide more information soon here and within the code repo.

Thank you!

**Comment by bruno-yamada** [comment]
@mko-x 
The image on docker-hub is 9+ months old,
Can you please update it?
I can create a new issue if it is the preferred workflow
thanks

**Comment by mko-x** [comment]
Hey @bruno-yamada,
there will be no new build of alpine-idb-amd64 tag.

You should consider using the official clamav docker image and switch to it. I'm contributing to clamav itself now and will no longer update the images here - only for security reasons. If you use any image of clamav/clamav, the databases are preloaded at build time unless you add '_base' to the tag.
