### ISSUE TITLE
WARNING: Ignoring deprecated option SafeBrowsing at /etc/clamav/freshclam.conf:19

### ISSUE THREAD

**Issue by paul-mesnilgrente** [mko-x/docker-clamav#133]
**Describe the bug**
There is a warning in the logs of latest (1.0.3) tag: 

> WARNING: Ignoring deprecated option SafeBrowsing at /etc/clamav/freshclam.conf:19

**To Reproduce**
Launch the docker container 1.0.3

**Expected behavior**
I would expect no warnings

**Host (please complete the following information):**
 - Alpine, I didn't check the other OS but I assume it's not host related

**Comment by mko-x** [comment]
Thank you very much for the hint @paul-mesnilgrente ! Should be fixed in V 1.0.4
