### ISSUE TITLE
Outdated ClamAV version in Alpine main

### ISSUE THREAD

**Issue by MohamedSahbi** [mko-x/docker-clamav#135]
Hello Mko,

I am using Alpine main in my cloned [repos](https://github.com/MohamedSahbi/docker-clamav) (due to openshift adaption)
I ran into this messages
```
Tue Aug 24 08:43:34 2021 -> ^Your ClamAV installation is OUTDATED!
Tue Aug 24 08:43:34 2021 -> ^Local version: 0.103.2 Recommended version: 0.103.3
Tue Aug 24 08:43:34 2021 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav 
```

When checking the packages in alpinelinux , I found that the version 0.103.3 is available only in alpine v3.14. see https://pkgs.alpinelinux.org/packages?name=clamav&branch=v3.14

So, I updated my version and it is working.  https://github.com/MohamedSahbi/docker-clamav/blob/master/Dockerfile

Also, I ran into proxy issue because I am using it behind enterprise proxy.
```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: network error (check Internet connection and firewall)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: network error (check Internet connection and firewall)
```
"I" solved it by rewriting https proxy to http, see https://github.com/MohamedSahbi/docker-clamav/blob/master/Dockerfile#L4
This issue started with alpine v3.13 and it is not solved yet.

Should I create PR for it? or this issue is not encountered by anyone else?

**Comment by mko-x** [comment]
Thank you for the PR - merged for 1.0.5 - fixe by #137
