### ISSUE TITLE
Feature Request:  add environment variable to delay clamav and freshclam startup

### ISSUE THREAD

**Issue by millerthegorilla** [mko-x/docker-clamav#136]
When I start my containers, there is a high memory usage, and this sometimes causes issues.  It would be nice to be able to specify an environment variable to the run command, that will delay clamav and freshclam by a number of seconds.

To do this, /bootstrap.sh in the filesystem root could have a 'sleep ${CLAM_START_DELAY}' just before the lines where clam and freshclam start and fork.

Does this make sense, and should I create a pull request?

**Comment by mko-x** [comment]
Please provide the changes for all the images - so - that we have a consistent behavior for each image. If you have questions for the images you may not use don't hesitate to ask for help here.

**Comment by millerthegorilla** [comment]
Ok, thanks.  Sorry I have been tied up, I will have a look now.

**Comment by millerthegorilla** [comment]
Ok, I have tried the stretch and buster images and I get the same error when I run them - 
```
LibClamAV Error: cli_loaddbdir(): No supported database files found in /var/lib/clamav
```
I think this may be because of the following in the dockerfile
```
# initial update of av databases
# disabled - see https://github.com/mko-x/docker-clamav#prefer-alpine-idb-amd64
#RUN { wget -O /var/lib/clamav/main.cvd http://database.clamav.net/main.cvd && \
#    wget -O /var/lib/clamav/daily.cvd http://database.clamav.net/daily.cvd && \
#    wget -O /var/lib/clamav/bytecode.cvd http://database.clamav.net/bytecode.cvd && \
#    chown clamav:clamav /var/lib/clamav/*.cvd } || { echo DB Initialisation failed }
```
So when clamd starts, there are no virus definitions.
So I ran freshclam in the bootstrap.sh using the following syntax:
```
 freshclam -d --on-update-execute="clamd &"
```
and the virus definitions were in place before clamd ran.  This allowed me to start the container, as before it wouldn't start.
I then got an error in the freshclam log stating that 
```
WARNING: Clamd was NOT notified: Cannot connect to clamd through 
/var/run/clamav/clamd.ctl connect(): permission denied
```
According to the arch wiki here...
```
https://wiki.archlinux.org/title/ClamAV
```
The first error - No supported database files found in /var/lib/clamav - is due to : 
```
This happens because of mismatch between /etc/clamav/freshclam.conf setting DatabaseDirectory and /etc/clamav/clamd.conf setting DatabaseDirectory. 
```
and the second - clamd not notified : 
```
Add a sock file for ClamAV:

# touch /run/clamav/clamd.ctl
# chown clamav:clamav /run/clamav/clamd.ctl

Then, edit /etc/clamav/clamd.conf - uncomment this line:

LocalSocket /run/clamav/clamd.ctl
```
All of this is with the standard, unchanged configuration as I cloned the repo.   When clamd starts in bootstrap.sh, it should create the socket file, before freshclam tries to use it, but clamd is not starting because either a.  it can't find virus definitions. or b. because of a mismatch between conf file locations, which may be a consequence of the way that you have organised the import of clamav.conf files in envconfig.sh, although that file is missing from the debian stretch directory, and I still get the database missing error.
Most likely, bootstrap.sh should start freshclam using the  --on-update-execute="clamd &" syntax and the error about not being able to access /var/run/clamav/clamd.ctl should be ignored, as the second time that freshclam runs, it should find the socket ok.

As for my own feature request, I want to make the following change...
```
function clam_start () {
# start clam service itself and the updater in background as daemon
    freshclam -d  --on-update-execute="clamd &"
}

if [[ ! -z "${CLAM_DELAY}" ]]
then
	(sleep ${CLAM_DELAY} && clam_start) &
else
	clam_start
fi
```
or something like this, as I could fork the function, instead of the individual commands.  I need to test it.
if I don't hear from you, I will go ahead and make the changes, and submit a pull request.

**Comment by millerthegorilla** [comment]
Freshclam fails on stretch, as ....
Currently, every version from ClamAV 0.99 and down, including all patch versions, are unsupported, and are actively blocked from downloading new updates.
https://askubuntu.com/questions/1214151/ubuntu-clamav-freshclam-cant-download-main-cvd

**Comment by millerthegorilla** [comment]
Cannot test alpine, due to ratelimiting from clamav.  As soon as I have tested it tomorrow, if it works, I will make a pull request.

**Comment by millerthegorilla** [comment]
Ok, I have made a pull request.

**Comment by mko-x** [comment]
Thank you very muchfor the new feature,I'm appreciating your work done 👍🏼

**Comment by millerthegorilla** [comment]
I am grateful for your work on maintaining the image and am glad to be of help, and, of course, helpful to my own project.
