### ISSUE TITLE
Question to help fix a configuration 

### ISSUE THREAD

**Issue by Aceriz** [mko-x/docker-clamav#173]
I am wondering if you will be able to help me out with something. 

I have setup the Docker-Clamav via unraid. 
I am using the setup to allow daemon scanning of my nextcloud docker. 

I am unfortunately getting the following error in the log. I am not sure how I would go about changing the check time so that it does not  trigger the blocking of database update. 

Logs below

Thu Nov 11 05:53:25 2021 -> ClamAV update process started at Thu Nov 11 05:53:25 2021
Thu Nov 11 05:53:26 2021 -> ^Your ClamAV installation is OUTDATED!
Thu Nov 11 05:53:26 2021 -> ^Local version: 0.102.4 Recommended version: 0.103.4
Thu Nov 11 05:53:26 2021 -> DON'T PANIC! Read https://www.clamav.net/documents/upgrading-clamav
Thu Nov 11 05:53:26 2021 -> daily database available for update (local version: 26349, remote version: 26350)
Thu Nov 11 05:53:28 2021 -> Testing database: '/var/lib/clamav/tmp.da8a6/clamav-657c926e1e7e31ed3ddaa24ef0748942.tmp-daily.cld' ...
Thu Nov 11 05:53:33 2021 -> Database test passed.
Thu Nov 11 05:53:33 2021 -> daily.cld updated (version: 26350, sigs: 1943487, f-level: 90, builder: raynman)
Thu Nov 11 05:53:34 2021 -> main.cld database is up to date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
Thu Nov 11 05:53:34 2021 -> bytecode.cld database is up to date (version: 333, sigs: 92, f-level: 63, builder: awillia2)

Thanks in Advance for your help

**Comment by mko-x** [comment]
Hey @Aceriz 
Thank you for your question.
I see no error in the logs but a warning about the clamav version, do you mean that?

**Comment by Aceriz** [comment]
Hi yes, 
the clamav version.  It is saying that it is out of date. without being able to update. . not sure what I am messing up. 
Of if there is something I need to change to allow it to update  as it had been working.

**Comment by mko-x** [comment]
Which image of docker-clamav are you working with?
