### ISSUE TITLE
Clamd was NOT notified: Can't connect to clamd through /var/run/clamav/clamd.ctl: Connection refused

### ISSUE THREAD

**Issue by AmineTali** [mko-x/docker-clamav#174]
**Describe the bug**
When running my clamav image i get this error several times :
```
Clamd was NOT notified: Can't connect to clamd through /var/run/clamav/clamd.ctl: Connection refused
```
![image](https://user-images.githubusercontent.com/89411896/141845834-e210a343-ecbf-4d7b-8c2b-9a38ca6df823.png)

The clamd.ctl file is created : ls -l /var/run/clamav/
![image](https://user-images.githubusercontent.com/89411896/141844946-02f49f08-0454-4e71-a8a7-9c7600658d78.png)

**My clamd.conf**
```
#Automatically Generated by clamav-daemon postinst
#To reconfigure clamd run #dpkg-reconfigure clamav-daemon
#Please read /usr/share/doc/clamav-daemon/README.Debian.gz for details
LocalSocket /var/run/clamav/clamd.ctl
FixStaleSocket true
LocalSocketGroup clamav
LocalSocketMode 666
.
.
.
TCPSocket 3310
```

**Image :**
 [debian:buster-slim](https://github.com/mko-x/docker-clamav/tree/master/debian/buster)

**Comment by mko-x** [comment]
Seems like clamd wasn't started yet.  Did you try the alpine image as well?

**Comment by AmineTali** [comment]
clamd is started. Now the error appears occasionally. 
No, I haven't tried the alpine image.

**Comment by mko-x** [comment]
Hmm, seems like a race condition on startup.

I recommend using the alpine image.

**Comment by AmineTali** [comment]
thank you for your reply :)
