### ISSUE TITLE
Container Won't Start Up

### ISSUE THREAD

**Issue by khollycap** [mko-x/docker-clamav#176]
Hello, I have been using this image on an Azure Container Instance since last November with no issues. However, when I went to update my container yesterday, it got stuck in the deployment process until timing out. I pulled the same image to my local machine and during startup it gets stuck at the following spot: 
![image](https://user-images.githubusercontent.com/86684837/151006497-6a8e937e-5e73-475f-98ee-d3d207f218d9.png)

Previously, I was using the default that is pulled with mkodockx/docker-clamav, but I also tried alpine, buster, and latest tags once I ran into the issues. It seems to happening with all version for me. 

Please let me know the steps I can take to remediate this issue.

**Comment by mko-x** [comment]
Hello @khollycap ,
thank you very much for posting your issue. I can reproduce the error.

It looks like an interruption of the connection during the database download.

**Comment by mko-x** [comment]
As I read the infos of clamav Discord, there is a various blocking of clients established via Cloudflare.

So the old versions are blocked, there is rate limiting per client and per IP as well. I'm not sure somewhat more is blocked

**Comment by mko-x** [comment]
Did you try the alpine-edge version? It has the latest available clamav version integrated. For me that one works.

**Comment by mko-x** [comment]
The alpine image uses clamav in version 0.103.3-r0.
The alpine edge image uses clamav in version 0.104.2-r0

**Comment by khollycap** [comment]
![image](https://user-images.githubusercontent.com/86684837/151872758-353b592a-874a-4194-8daf-2df943f4336e.png)
That one gets stuck on the daily database download for me.

**Comment by mko-x** [comment]
Well I was able to reproduce the error again, it seems to me it has something to do with docker desktop.

If I run it with docker from terminal, there is no error. Could you try following in your terminal:

```bash
docker run -d mkodockx/docker-clamav:alpine
```

**Comment by mko-x** [comment]
Started from docker desktop:

<img width="474" alt="grafik" src="https://user-images.githubusercontent.com/10264942/151877650-48e9261a-791d-4325-a299-1283ef1a829d.png">

Started from terminal exact same image:
![grafik](https://user-images.githubusercontent.com/10264942/151877695-7078582c-4f63-4af6-ac05-3957b01c3beb.png)

**Comment by khollycap** [comment]
![image](https://user-images.githubusercontent.com/86684837/151877706-0482f177-81ae-4bb8-b5dd-b6db823c8779.png)
I got this ^ error after running that command

**Comment by mko-x** [comment]
You need to wait a moment, clamd needs to start first - freshclam will try again after some time

**Comment by mko-x** [comment]
I'm not sure but it might be because of the different std attachment and tty configuration:

From CLI:
```json
[
    {
        "AppArmorProfile": "",
        "Args": [
        ],
        "Config": {
            "AttachStderr": false,
            "AttachStdin": false,
            "AttachStdout": false,
            "Cmd": [
                "/bootstrap.sh"
            ],
            "Domainname": "",
            "Entrypoint": null,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "ExposedPorts": {
                "3310/tcp": {
                }
            },
            "Hostname": "e8da6560714a",
            "Image": "mkodockx/docker-clamav:alpine",
            "Labels": {
                "maintainer": "Markus Kosmal <code@m-ko.de>"
            },
            "OnBuild": null,
            "OpenStdin": false,
            "StdinOnce": false,
            "Tty": false,
            "User": "clamav",
            "Volumes": null,
            "WorkingDir": ""
        },
        [...]
        
    }
]
```

From Docker Desktop:
```json
[
    {
        "AppArmorProfile": "",
        "Args": [
        ],
        "Config": {
            "AttachStderr": true,
            "AttachStdin": false,
            "AttachStdout": true,
            "Cmd": [
                "/bootstrap.sh"
            ],
            "Domainname": "",
            "Entrypoint": null,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "ExposedPorts": {
                "3310/tcp": {
                }
            },
            "Hostname": "ac6770f990ac",
            "Image": "mkodockx/docker-clamav:alpine",
            "Labels": {
                "maintainer": "Markus Kosmal <code@m-ko.de>"
            },
            "OnBuild": null,
            "OpenStdin": false,
            "StdinOnce": false,
            "Tty": true,
            "User": "clamav",
            "Volumes": null,
            "WorkingDir": ""
        },
        [...]
    }
]
```
