### ISSUE TITLE
Reasoning for non-default config options

### ISSUE THREAD

**Issue by eht16** [mko-x/docker-clamav#177]
I'm currently in the process of migrating to the official ClamAV Docker image and comparing the configuration of this(alpine version) and the official image.

As expected, most things are equal. But a few config options differ from the ClamAV defaults.

In particular, I'm interested if it is still known what were the reasons for the following options:

- `AlertBrokenExecutables yes`
- `DisableCertCheck yes`
- `DetectPUA yes`
- `ExcludePUA NetTool`
- `ExcludePUA PWTool`

Do you remember why the PUA categories `NetTool` and `PWTool` were excluded? Too many false positives?
Did `DisableCertCheck` caused problems?

Thank you for your support!

**Comment by mko-x** [comment]
Hey @eht16 ,

I'm not sure about any of the config values you mentioned above.

**Comment by eht16** [comment]
Hey @mko-x,

ok, thanks.
Then I have to figure out myself whether to keep or drop these options :).
