### ISSUE TITLE
Root Login to Container

### ISSUE THREAD

**Issue by Leviani** [mko-x/docker-clamav#183]
Hi,
I did pull the Docker Image and deployed it into an Azure Container Instance.
Since I would like to do some changes / updates with any package manager (e.g. apt-get), I need root access. The same is needed if you want to restart the running freshclam service.

The default login is "clamav" and as soon as I try to switch with "su -" I need a password.

**Comment by mko-x** [comment]
You may consider forking this repo change the stuff you need directly in the Dockerfiles

**Comment by mko-x** [comment]
Docker is not expected to allow interactive root acceess. As you may need the stuff from a packagemanager frquently you should suggest to add the stuff within the Dockerfile - or you can fork directly from the image and add the stuff you need to your Dockerfile.

More info here https://stackoverflow.com/questions/56837236/set-password-for-root-user-in-docker

and here https://www.secpod.com/blog/watch-out-for-alpine-linux-docker-image-root-login-vulnerability/

**Comment by mko-x** [comment]
Yes probably. Most running frameworks like Azure and Kubernetes restrict the access within the containers for security reasons.
