### ISSUE TITLE
docker image rebuild

### ISSUE THREAD

**Issue by ITler** [mko-x/docker-clamav#190]
Hello,

`clamav` itself recently has a [CVE](https://blog.clamav.net/2023/02/clamav-01038-01052-and-101-patch.html)

Would you mind publishing new image builds to docker hub - especially the `alpine-idb-amd64` version, please?

Thank you!

**Comment by ITler** [comment]
Sorry, didn't see the comment in README

**Comment by mko-x** [comment]
Please find all current stuff at https://github.com/Cisco-Talos/clamav now.
