### ISSUE TITLE
Update ClamAV

### ISSUE THREAD

**Issue by midnightcodr** [mko-x/docker-clamav#26]
Hi I would like to bring ClamAV to the newest version because I am seeing this in the log
```
Local version: 0.100.3 Recommended version: 0.101.4
```

Building locally fails with the following error:

```
E: Package 'libclamunrar7' has no installation candidate
```

Please advise. Thank you.

**Comment by giulianfazio** [comment]
Replace `libclamunrar7` with `libclamunrar9`. That should solve your issue

**Comment by midnightcodr** [comment]
That did it. Thanks @giulianfazio.
