### ISSUE TITLE
Deployment failing to Azure Container Instance

### ISSUE THREAD

**Issue by davidheerema** [mko-x/docker-clamav#36]
Creating the Azure container instance using:
az container create --resource-group groupname --name containername --image mk0x/docker-clamav:alpine --dns-name-label containerdnsname --ports 80 3110

It creates successfully the but the container fails with the following logs presented:
az container logs --resource-group groupname --name containername --follow
Wed Jan 22 16:17:54 2020 -> ClamAV update process started at Wed Jan 22 16:17:54 2020
Wed Jan 22 16:17:54 2020 -> daily database available for download (remote version: 25703)
Wed Jan 22 16:18:03 2020 -> ^Mirror https://database.clamav.net is not synchronized.
Wed Jan 22 16:18:03 2020 -> !Unexpected error when attempting to update database: daily
Wed Jan 22 16:18:03 2020 -> ^fc_update_databases: fc_update_database failed: Up-to-date (1)
Wed Jan 22 16:18:03 2020 -> !Database update process failed: Up-to-date (1)
Wed Jan 22 16:18:03 2020 -> !Update failed.
WARNING: Ignoring deprecated option DetectBrokenExecutables at /etc/clamav/clamd.conf:30
LibClamAV Error: cli_loaddbdir(): No supported database files found in /store
Wed Jan 22 16:18:04 2020 -> !Can't open file or directory

I have also tried creating it with a persistent store for /store but it doesn't make a difference, still fails for same reason.

This is off of the alpine branch - master seems to work fine.

**Comment by elijahmuha** [comment]
Seeing the same issue in AWS. Ran locally with docker-compose with the same result:

`docker-compose.yml`:
```
version: "3"

services:
  clam-test:
    image: mkodockx/docker-clamav:alpine
```
Result:
```
$ docker-compose run clam-test
Creating network "clamav_default" with the default driver
Thu Jan 23 14:14:39 2020 -> ClamAV update process started at Thu Jan 23 14:14:39 2020
Thu Jan 23 14:14:39 2020 -> daily database available for download (remote version: 25704)
Time: 2.4s, ETA; 0.0s [=======================================>] 55.28MiB/55.28MiB
Thu Jan 23 14:14:42 2020 -> ^Mirror https://database.clamav.net is not synchronized.
Thu Jan 23 14:14:42 2020 -> !Unexpected error when attempting to update database: daily
Thu Jan 23 14:14:42 2020 -> ^fc_update_databases: fc_update_database failed: Up-to-date (1)
Thu Jan 23 14:14:42 2020 -> !Database update process failed: Up-to-date (1)
Thu Jan 23 14:14:42 2020 -> !Update failed.
WARNING: Ignoring deprecated option DetectBrokenExecutables at /etc/clamav/clamd.conf:30
LibClamAV Error: cli_loaddbdir(): No supported database files found in /store
Thu Jan 23 14:14:42 2020 -> !Can't open file or directory
```

**Comment by mko-x** [comment]
Does the error reoccur? I noticed some connection errors with the update servers earlier.

**Comment by davidheerema** [comment]
No, still failing due to same error.  I have opened a bug with clamAV on
the issue which they have recognized.
https://bugzilla.clamav.net/show_bug.cgi?id=12469

**Comment by davidheerema** [comment]
It seems like the Devs at ClamAV have published a fix for the issue, however your repo doesn't reference the latest build with this fix in it yet.  See https://bugzilla.clamav.net/show_bug.cgi?id=12469

**Comment by scp-mb** [comment]
We've been hit by the same issue now.

**Comment by mko-x** [comment]
The builds should be delivered wit the latest fixes from the different mirrors provided at docker hub after the automated builds finished.
