### ISSUE TITLE
What's the best strategy for handling scanning other containers with this?

### ISSUE THREAD

**Issue by Leopere** [mko-x/docker-clamav#37]
It doesn't look like the `docker-compose.yml` allows this thing to do anything.  Am I missing something?

**Comment by mko-x** [comment]
You need any kind of container using the clamav engine as stated in the about.

> Dockerized open source antivirus daemons for use with

    file sharing containers like Nextcloud or
    to use it via a REST proxy like @solita made clamav-rest or
    to directly connect to clamav via TCP port 3310

So if you need more information, you might want to look at https://github.com/solita/clamav-rest for how clamav can be used in a container.

**Comment by Leopere** [comment]
Thanks
