### ISSUE TITLE
Freshclam failing to update db's

### ISSUE THREAD

**Issue by PleaseStopAsking** [mko-x/docker-clamav#38]
Starting this morning, freshclam is failing to update the db's with the below errors. Doing some digging online and it seems that this might be caused by curl not being able to validate the certificate used by the mirrors.

If I add the ca-certificates package to the build, the issue goes away. I assume there is another fix to reduce footprint but it is not obvious to me at the moment.

![image](https://user-images.githubusercontent.com/35308946/75166463-e6f2cb80-56f1-11ea-8775-7520f9ff0dee.png)

**Comment by davidheerema** [comment]
I am getting this as well.

**Comment by davidheerema** [comment]
@PleaseStopAsking can you detail how you fixed this temporarily?

**Comment by PleaseStopAsking** [comment]
@davidheerema I added a new line to the apt-get install section of the dockerfile which installs the ca-certificates packages.

**Comment by davidheerema** [comment]
@PleaseStopAsking I hate to _keep asking_ but do you have the line?

**Comment by PleaseStopAsking** [comment]
@davidheerema Here you go. You can remove `=${CA_VERSION}` to just install the latest version if desired.

![image](https://user-images.githubusercontent.com/35308946/75266219-0526fd00-57c0-11ea-91e4-7bb05190912c.png)

**Comment by mko-x** [comment]
Would you mind placing a pull request? @davidheerema || @PleaseStopAsking

**Comment by Capusjon** [comment]
to fix it right now you could use the command line to install ca-certificates inside the docker container.

docker exec -it **clamav or whaterver your container is called** bash 
then: apt-get -y install ca-certificates
exit
Now these errors should be gone and you can download updates.

**Comment by mko-x** [comment]
Fixed by #42 - thank you very much @Capusjon
