### ISSUE TITLE
bootstrap.sh bug

### ISSUE THREAD

**Issue by clausmuus** [mko-x/docker-clamav#4]
Hi,

there is a bug in the bootstrap.sh. Here is a fix:
```
--- bootstrap.sh.orig   2017-07-04 15:54:54.000000000 +0200
+++ bootstrap.sh        2017-07-05 10:29:14.749407999 +0200
@@ -15,7 +15,7 @@

 # define shutdown helper
 function shutdown() {
-    trap "" SUBS
+    trap "" SIGINT

     for single in $pidlist; do
         if ! kill -0 $pidlist 2>/dev/null; then
@@ -28,7 +28,7 @@
 }

 # run shutdown
-trap terminate SUBS
+trap shutdown SIGINT
 wait

 # return received result

```

**Comment by mko-x** [comment]
Thank you very much.

Fixed in https://github.com/mko-x/docker-clamav/commit/e306227c9db8b4a8c956b5c26993df885fbf7069

**Comment by clausmuus** [comment]
Hi,

you have overlook the change of 'terminate' to 'shutdown' in the second change of my patch.

**Comment by mko-x** [comment]
arr, that's why it didn't work - thank you again.

See https://github.com/mko-x/docker-clamav/commit/0a5302ae71e6d9d90f88e88f90e44747a366c28a
