### ISSUE TITLE
Alpine docker image contains outdated ClamAV

### ISSUE THREAD

**Issue by petertsu** [mko-x/docker-clamav#45]
Thu Apr  9 14:13:39 2020 -> ClamAV update process started at Thu Apr  9 14:13:39 2020
Thu Apr  9 14:13:39 2020 -> ^Your ClamAV installation is OUTDATED!
Thu Apr  9 14:13:39 2020 -> ^Local version: 0.102.1 Recommended version: 0.102.2

**Comment by mko-x** [comment]
Which version of docker-clamav are you using?

**Comment by petertsu** [comment]
mk0x/docker-clamav:alpine              9d12f0149450        11 days ago         16.3MB

**Comment by mko-x** [comment]
See #39 

Take a look at latest stable alpine (3.11) packages and look for clamav.
See [here](https://pkgs.alpinelinux.org/packages?name=clamav&branch=v3.11)

Alpine 3.11 installs ClamAV 0.102.1-r0 as for today.

If you want the latest clamav, you need to use unstable alpine edge.

Maybe I create another branch for alpine edge users.

**Comment by mko-x** [comment]
See new alpine-edge version [here](https://github.com/mko-x/docker-clamav/tree/alpine-edge) or use it directly
```bash
     docker run mkodockx/docker-clamav:alpine-edge
```

**Comment by petertsu** [comment]
@mko-x  Thanks.  Maybe you need to contact Carlo Landmeter  to publish latest clamav package for Alpine
