### ISSUE TITLE
/store/tmp filling diskspace

### ISSUE THREAD

**Issue by RappC** [mko-x/docker-clamav#48]
The /store/tmp directory is filling up with `clamav-*.tmp` files. 

Can't the container itself take care of cleaning up those files?

**Comment by mko-x** [comment]
The container aims at let clamav do, so the clamav default settings for this case are LeaveTemporaryFiles (no). I wonder that you have the files.

You could try to force that behaviour by explicitly in a custom configuration with

    LeaveTemporaryFiles no

See https://linux.die.net/man/5/clamd.conf too.
