### ISSUE TITLE
latest_exit is always zero on bootstrap script

### ISSUE THREAD

**Issue by ergoithz** [mko-x/docker-clamav#5]
Var `latest_exit`is returned but never updated, as `exitcode` is updated instead.

https://github.com/mko-x/docker-clamav/blob/742778531c16f26565fac04de31fd10da47d4da5/bootstrap.sh#L14

https://github.com/mko-x/docker-clamav/blob/742778531c16f26565fac04de31fd10da47d4da5/bootstrap.sh#L23

https://github.com/mko-x/docker-clamav/blob/742778531c16f26565fac04de31fd10da47d4da5/bootstrap.sh#L35

**Comment by mko-x** [comment]
Thank you for the hint.
