### ISSUE TITLE
rest api

### ISSUE THREAD

**Issue by thdotnet** [mko-x/docker-clamav#6]
Hi,

I can see that the container is running and exposing an endpoint on 3310. How can I send a file using the rest api? or does it offer a User Interface that I can use to upload / check the files?

**Comment by mko-x** [comment]
Hi @thdotnet,
this image just offers dockerized freshclam and clam(d) daemons running within a container. 

If you want to make use of it via REST, you should connect it via a REST proxy (possibly as docker container).

@lokori created a good one that runs with this docker-clamav as docker image https://hub.docker.com/r/lokori/clamav-rest/ (source: https://github.com/lokori/clamav-rest).

Regards 👍
