### ISSUE TITLE
Cannot directly connect to clamav via TCP port 3310

### ISSUE THREAD

**Issue by BillyTheCowBoy** [mko-x/docker-clamav#60]
**Hi , i try to access clamav in browser : localhost:3310 , but it keep returning "This page isn’t working"**

**i have run this** 
docker run -d -p 3310:3310 mk0x/docker-clamav:alpine-edge

**i have check the log message. it seems like Clamd cannot be connect.**

[bootstrap] Initial clam DB download.
Sat Jul 18 06:18:21 2020 -> ClamAV update process started at Sat Jul 18 06:18:21 2020
Sat Jul 18 06:18:21 2020 -> daily database available for download (remote version: 25876)
Sat Jul 18 06:18:39 2020 -> Testing database: '/store/tmp.70df0/clamav-d6228cd95d4d5ce9fa7a30df36c31fa1.tmp-daily.cvd' ...
Sat Jul 18 06:18:48 2020 -> Database test passed.
Sat Jul 18 06:18:48 2020 -> daily.cvd updated (version: 25876, sigs: 3467263, f-level: 63, builder: raynman)
Sat Jul 18 06:18:48 2020 -> main database available for download (remote version: 59)
Sat Jul 18 06:19:13 2020 -> Testing database: '/store/tmp.70df0/clamav-f96988d52853263abc2e60c402ffb19f.tmp-main.cvd' ...
Sat Jul 18 06:19:18 2020 -> Database test passed.
Sat Jul 18 06:19:18 2020 -> main.cvd updated (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
Sat Jul 18 06:19:18 2020 -> bytecode database available for download (remote version: 331)
Sat Jul 18 06:19:18 2020 -> Testing database: '/store/tmp.70df0/clamav-3db0d14a91c6446fd3fe828da611ba01.tmp-bytecode.cvd' ...
Sat Jul 18 06:19:18 2020 -> Database test passed.
Sat Jul 18 06:19:18 2020 -> bytecode.cvd updated (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
Sat Jul 18 06:19:18 2020 -> safebrowsing database available for download (remote version: 49191)
Sat Jul 18 06:19:27 2020 -> Testing database: '/store/tmp.70df0/clamav-92d02f11d475c4e11c9f63898002f7d3.tmp-safebrowsing.cvd' ...
Sat Jul 18 06:19:30 2020 -> Database test passed.
Sat Jul 18 06:19:30 2020 -> safebrowsing.cvd updated (version: 49191, sigs: 2213119, f-level: 63, builder: google)
Sat Jul 18 06:19:30 2020 -> ^Clamd was NOT notified: Can't connect to clamd through /tmp/clamd.sock: No such file or directory
[bootstrap] Schedule freshclam DB updater.
[bootstrap] Run clamav daemon
Sat Jul 18 06:19:50 2020 -> Limits: Global time limit set to 120000 milliseconds.
Sat Jul 18 06:19:50 2020 -> Limits: Global size limit set to 314572800 bytes.
Sat Jul 18 06:19:50 2020 -> Limits: File size limit set to 104857600 bytes.
Sat Jul 18 06:19:50 2020 -> Limits: Recursion level limit set to 30.
Sat Jul 18 06:19:50 2020 -> Limits: Files limit set to 50000.
Sat Jul 18 06:19:50 2020 -> Limits: MaxEmbeddedPE limit set to 41943040 bytes.
Sat Jul 18 06:19:50 2020 -> Limits: MaxHTMLNormalize limit set to 41943040 bytes.
Sat Jul 18 06:19:50 2020 -> Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Sat Jul 18 06:19:50 2020 -> Limits: MaxScriptNormalize limit set to 5242880 bytes.
Sat Jul 18 06:19:50 2020 -> Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Sat Jul 18 06:19:50 2020 -> Limits: MaxPartitions limit set to 128.
Sat Jul 18 06:19:50 2020 -> Limits: MaxIconsPE limit set to 200.
Sat Jul 18 06:19:50 2020 -> Limits: MaxRecHWP3 limit set to 16.
Sat Jul 18 06:19:50 2020 -> Limits: PCREMatchLimit limit set to 10000.
Sat Jul 18 06:19:50 2020 -> Limits: PCRERecMatchLimit limit set to 10000.
Sat Jul 18 06:19:50 2020 -> Limits: PCREMaxFileSize limit set to 26214400.
Sat Jul 18 06:19:50 2020 -> Archive support enabled.
Sat Jul 18 06:19:50 2020 -> AlertExceedsMax heuristic detection disabled.
Sat Jul 18 06:19:50 2020 -> Heuristic alerts enabled.
Sat Jul 18 06:19:50 2020 -> Portable Executable support enabled.
Sat Jul 18 06:19:50 2020 -> ELF support enabled.
Sat Jul 18 06:19:50 2020 -> Alerting on broken executables enabled.
Sat Jul 18 06:19:50 2020 -> Mail files support enabled.
Sat Jul 18 06:19:50 2020 -> OLE2 support enabled.
Sat Jul 18 06:19:50 2020 -> PDF support enabled.
Sat Jul 18 06:19:50 2020 -> SWF support enabled.
Sat Jul 18 06:19:50 2020 -> HTML support enabled.
Sat Jul 18 06:19:50 2020 -> XMLDOCS support enabled.
Sat Jul 18 06:19:50 2020 -> HWP3 support enabled.
Sat Jul 18 06:19:50 2020 -> Self checking every 600 seconds.
Sat Jul 18 06:19:50 2020 -> Set stacksize to 1048576

**Comment by PAX523** [comment]
Are you certain that the daemon also provides a web service? I'm not aware about that. As far as I know, it only provides a TCP service with a custom protocol. If you want to test that it's available you could use telnet:

```
telnet localhost:3310

PING
```

Response:

```
PONG
```

These are the possible commands: https://linux.die.net/man/8/clamd

**Comment by mko-x** [comment]
As @PAX523 already mentioned, there is no web service directly via browser available.

You cannot connect directly via a browser. You need to follow the ClamAV or clamd Protocol.

See [clamd protocol docs](https://linux.die.net/man/8/clamd) for more info.

If you want to use it directly in the browser you should at least use a REST proxy.

As you could read in the [README](https://github.com/mko-x/docker-clamav/blob/master/README.md) of this image.

> to use it via a REST proxy like @solita made [clamav-rest](https://github.com/solita/clamav-rest)

This is not an issue of this docker image.
