### ISSUE TITLE
Redhat UBI image support

### ISSUE THREAD

**Issue by Kenzku** [mko-x/docker-clamav#61]
Hej,

I saw your docker file is using `debian:stretch-slim` as based image from https://hub.docker.com/r/mkodockx/docker-clamav/dockerfile. I was wonder do you have a ClamAV based on RedHat image or instruction how to make a RedHat UBI based image ClamAV please?

**Comment by mko-x** [comment]
I do not have any experience with RedHat UBI yet. This image is provided on other bases as well (see the other branches, like very tiny alpine image).

You could use this image with a RedHat UBI based image as well as two containers in one docker system connected to each other.

Why should there be a need for an extra RedHat UBI image, why do you need this?

You can always feel free to provide a new image version and I will integrate it in this repo.

But my time is short and I take care about this repo in my spare time, so you may try it on your own and if you have problems, you could ask me here. (Maybe I will have a look at it, but there is no promise)
