### ISSUE TITLE
How to verify if auto-update is working?

### ISSUE THREAD

**Issue by sebader** [mko-x/docker-clamav#62]
I am running this image (thanks a lot for it!) successfully inside an Azure Container instance. At startup I can see the freshclam running and downloading the latest av definitions. Then clamav itself starts. So far so good. 
My question now is: How can I verify that the auto-update of freshclam works? I didn't see any log entries in regards to the update or anything?!

I could connect to the container. Is there any command I could run to see the version of the currently installed definitions?

Thanks!

**Comment by markus-seidl** [comment]
As far as I can see, this image doesn't autoupdate.

**Comment by gregorko** [comment]
I use this command inside the container to look at the log. It should also contain information about the used definitions:
``/bin/cat /var/log/clamav/freshclam.log``

**Comment by sebader** [comment]
hmm thanks @gregorko but this just gives me:

    cat: can't open '/var/log/clamav/freshclam.log': No such file or directory

This is probably not a good sign?!

**Comment by sebader** [comment]
@mko-x this gives me a different error:
![image](https://user-images.githubusercontent.com/11445087/91019779-d4e6dc80-e5f1-11ea-92bf-f6cabaab4813.png)

**Comment by mko-x** [comment]
What are the file stats?
`stat /var/lib/clamav/daily.cvd`
or
`file /var/lib/clamav/daily.cvd`
or
`ls -lh /var/lib/clamav/daily.cvd`

**Comment by sebader** [comment]
```
/ # ls -lh /var/lib/clamav/daily.cvd
ls: /var/lib/clamav/daily.cvd: No such file or directory
```

**Comment by mko-x** [comment]
🤔 
where is your bash at? are you inside of the clamav container or on the host?
which version/tag of mko-x/docker-clamav are you working with?

maybe try
`clamscan --version`

**Comment by sebader** [comment]
Running `mkodockx/docker-clamav:alpine` on an Azure Container Instance. So when connecting to it, it is inside the container. There is no bash so using /bin/sh

![image](https://user-images.githubusercontent.com/11445087/91604394-d9ebb900-e96e-11ea-9db6-87cb2b38ef3b.png)

**Comment by mko-x** [comment]
Could you provide contents of 
`ls -lah /store`
and output of
`sigtool --info /store/daily.cvd`

**Comment by sebader** [comment]
ok, this looks more promising:
![image](https://user-images.githubusercontent.com/11445087/91714135-61ae0f00-eb8b-11ea-8923-36bdc25e2c43.png)

**Comment by mko-x** [comment]
So I guess now you have a possibility to check if you have the latest database.

> Is there any command I could run to see the version of the currently installed definitions?

The question seems to be answered (:

**Comment by sebader** [comment]
yes, thank you!
