### ISSUE TITLE
Support for multi-arch dockerfiles

### ISSUE THREAD

**Issue by WhiteBahamut** [mko-x/docker-clamav#67]
Relates to #65 

Support for multi arch dockerfiles should include
- [x] amd64
- [x] arm32
- [x] arm64

--
- [x] build which pushes platform/arch images to dockerhub

Also all dockerfiles for each platform and distro should be in master , so that it is easier to understand the full setup of all distro-arch-combinations.

**Comment by WhiteBahamut** [comment]
Any time to look into the PR?

**Comment by mko-x** [comment]
Yes (:

**Comment by WhiteBahamut** [comment]
Let me know if I should also help with build settings :)
