### ISSUE TITLE
[Feature]  Specify Update time

### ISSUE THREAD

**Issue by Ryu945** [mko-x/docker-clamav#70]
I noticed it updates every 10 minutes by default.   It would be nice to be able to change this time.

**Comment by WhiteBahamut** [comment]
Same as #71 . I'd keep this one. as it has a better title

**Comment by mko-x** [comment]
This image sticks to default recommended update cycles of the developers of ClamAV.

You can easily create a new image from this one and add your custom configuration for freshclam.conf

like

```dockerfile
FROM mkodockx/docker-clamav
RUN "Checks 12" >> /etc/clamav/freshclam.conf;
```
'Checks' is the number of update cycles a day. If you use default ClamAV servers, you may update up to 4 times an hour.
See https://linux.die.net/man/5/freshclam.conf for more info or more custom settings.

You may provide a PR if you see it necessary for the main repo.

**Comment by Ryu945** [comment]
> RUN "Checks 12" >> /etc/clamav/freshclam.conf;

I added "Checks 12" to that file and it did not affect the update time.
