### ISSUE TITLE
Incorrect argument format

### ISSUE THREAD

**Issue by lrsppp** [mko-x/docker-clamav#75]
From docker logs:
```
[bootstrap] Initial clam DB download.
ERROR: Incorrect argument format for option LogSyslog
```

Content of `freshclam.conf`:

```
DatabaseDirectory /store/
LogSyslog yes
LogTime yes
PidFile /run/clamav/freshclam.pid
DatabaseOwner root
```

This bug appeared with the updated container. I am using the image inside a `docker-compose.yaml` with NextCloud.
Replaced `yes` with `true`, `1` didn't solve the issue.

**Comment by WhiteBahamut** [comment]
would close this one in favour of #76

**Comment by mko-x** [comment]
Could you please provide details of your `docker-compose.yaml` @lrsppp ?
