### ISSUE TITLE
Need to be able to change update timer

### ISSUE THREAD

**Issue by Ryu945** [mko-x/docker-clamav#81]
Updating every 10 minutes is a waste of bandwidth, RAM and CPU cycles.

**Comment by mko-x** [comment]
Which updating do you mean?

**Comment by Ryu945** [comment]
Every 10 minutes, it checks for new virus definitions.

**Comment by WhiteBahamut** [comment]
Just wondering how to achieve this best. Can you just use env vars in the conf files? Or does "fancy" regex and sed need to replace existing values in the conf files?

**Comment by WhiteBahamut** [comment]
best solution might be to mount config files. Instead of putting them into the image, they should be mounted. The repo can provide "default" files, but every have to mount them. So they can be changed as one like.

**Comment by mko-x** [comment]
This is what we are already doing. We provide default config files. If someone wants to use this in production, there are probably some configuration changes necessary. 

For a stable usage you should create your own Dockerfile and use this one here as parent.
Within your Dockerfile you can modify your configuration of clamd/freshclam/healtcheck etc.

**Comment by mko-x** [comment]
If this is a frequent problem, we could provide env vars to control it.

**Comment by WhiteBahamut** [comment]
Well, you dont need to derive your own image. Just user docker config (with swarm) or configmap with k8s. So there might be nothing to change. -OR- the dockerfile provide no config out of the box and one need to map a /config folder with own config files in it

**Comment by shaunakv1** [comment]
I agree on having defaults as they are right now, that way image stays easy to start on with. That being said, I am not sure recommended way to override configuration should be to mount a storage, and here are my few reasons: 

1. Complexity of mounting a storage in Cloud environment is usually much higher than setting environment variables. 

2. For deployments that don't already have cloud storage, reserving one just for this purpose is a waste of money. Services like azure allocate storage by quotas starting at 1gb and that's a waste of money just to do config files. 

3. Deploying multiple instances with different configurations is also a pain. Its much easier to set environment variables in pretty much all cloud environments. 

IMHO supporting environment variables for at-least  the more important configuration is the more practical way forward.

**Comment by WhiteBahamut** [comment]
As I said, I would use swarm config or ConfigMap in k8s, volume mapping would just be the "worst case" solution (agreed and was not aware of cloud cost :( ).
If config maps do not generate extra cost I would suggest the following:
- Add env vars for both config files `CLAM_CONFIG_FILE` and `FRESH_CONFIG_FILE`
- If these vars are set, use them from this location
- If these vars are empty, use default files from within the image

At least my bash knowladge is quite limited to do a better regex-sed-replace solution.

**Comment by mko-x** [comment]
As I see in freshclam.conf the default configuration is 
`Checks NUMBER
    Number of database checks per day.
    Default: 12 `

So where do you have update checks every ten minutes?

**Comment by avantida** [comment]
@Ryu945 
I see this in the our logging. Every 10 minutes indeed:
```
2020-11-02T09:35:41.9811943Z stdout F Mon Nov  2 09:35:41 2020 -> SelfCheck: Database status OK.
2020-11-02T09:45:42.1368013Z stdout F Mon Nov  2 09:45:42 2020 -> SelfCheck: Database status OK.
2020-11-02T09:55:42.2698007Z stdout F Mon Nov  2 09:55:42 2020 -> SelfCheck: Database status OK.
2020-11-02T10:05:42.4253976Z stdout F Mon Nov  2 10:05:42 2020 -> SelfCheck: Database status OK.
2020-11-02T10:15:42.5818453Z stdout F Mon Nov  2 10:15:42 2020 -> SelfCheck: Database status OK.
2020-11-02T10:25:42.7361833Z stdout F Mon Nov  2 10:25:42 2020 -> SelfCheck: Database status OK.
2020-11-02T10:35:42.8918623Z stdout F Mon Nov  2 10:35:42 2020 -> SelfCheck: Database status OK.
```
But I think this is not freshclam, but the `SELFCHECK` option in clamd.conf: https://linux.die.net/man/5/clamd.conf
```
SelfCheck NUMBER
Perform a database check.
Default: 1800
```
 So pretty harmless?

**Comment by Ryu945** [comment]
Isn't this self check a database update or is it something else?

**Comment by avantida** [comment]
Not the expert, yet I interpret this as the clamd process checking if the **local** database file was updated. While freshclam checks every two hours if it should download a new database file. 
So I do not think this Selfcheck is any significant use of CPU/RAM. And is is of no significance to bandwidth.

Still leaves the question of how much of the settings one would want to see as environment vars vs forking the repo and adjusting them to your needs in the *.conf files themselves.

**Comment by Ryu945** [comment]
Even if it is checking if the local database is updated, that is still way to often.   An update once a day for virus definitions and checking if virus definitions were updated is considered checking an extreme amount.  I would not have anything set any more then once a day.

**Comment by WhiteBahamut** [comment]
I'll try to make a PR this week with my suggestion to be able to provide own *.conf files. So one can provide own files with other settings. It won't require anyone to fork and built own image just because one value should be adjusted.

**Comment by WhiteBahamut** [comment]
Please check my PR. This should give us all the opions to configure freshclam and clamd as we wish, but still keeping als the possibilty for defaults from the image itself.

**Comment by Ryu945** [comment]
Update the example docker compose file to how it can be used.

**Comment by WhiteBahamut** [comment]
Environment vars are documented. Feel free to provide an update and I can put it in. I dont use compose anymore :)
