### ISSUE TITLE
Docker contain is making random volume again

### ISSUE THREAD

**Issue by Ryu945** [mko-x/docker-clamav#82]
I haven't found where in the code it is doing this but when I deploy mkodockx/docker-clamav:alpine, it is creating a random volume.   You had it fixed for a short time and then it started making that random volume again..

**Comment by mko-x** [comment]
Which version of the alpine image is creating the issue?

**Comment by Ryu945** [comment]
It was the latest one as of two weeks ago.

mkodockx/docker-clamav                     alpine              d8399f420d79        2 weeks ago         16.3MB

**Comment by mko-x** [comment]
If I run the latest image, there is no volume created. Which system are you running on?
Please provide detailed logs and information, should be visible there.

**Comment by Ryu945** [comment]
When you asked how old the latest image was and I saw it was 2 weeks old; I tried deleting the image and downloading a new one.   The image is no longer making a random volume.  You must have fixed it in a recent update.
