### ISSUE TITLE
Container cannot be started due to health check start period is too short

### ISSUE THREAD

**Issue by sammyhk** [mko-x/docker-clamav#83]
**Describe the bug**
Container cannot be started if do not have persistent volume due to the change of the start period (https://github.com/mko-x/docker-clamav/commit/6b837a347deddb8a04d783e02c410f882854fd2e#diff-ad6dc7c04f23afe88d0cd808022c0f03b443568ca479de506b38ebb757ff86fcR28). It got stopped when clamav still starting up to download newest update.
`docker logs -f <container id>` got following:
```
[bootstrap] Initial clam DB download.
Fri Oct 30 02:07:17 2020 -> ClamAV update process started at Fri Oct 30 02:07:17 2020
Fri Oct 30 02:07:17 2020 -> daily database available for download (remote version: 25972)
Fri Oct 30 02:08:56 2020 -> Testing database: '/var/lib/clamav/tmp.d8849/clamav-3f5df84d1dffe0dfb95a7563cbe75a43.tmp-daily.cvd' ...
Fri Oct 30 02:09:12 2020 -> Database test passed.
Fri Oct 30 02:09:12 2020 -> daily.cvd updated (version: 25972, sigs: 4336908, f-level: 63, builder: raynman)
Fri Oct 30 02:09:12 2020 -> main database available for download (remote version: 59)
<at this time, still downloading update, health check fail and container got killed>
```
`docker inspect <container id>` got following:
```
{
        ...
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2020-10-30T02:07:17.656967439Z",
            "FinishedAt": "2020-10-30T02:10:30.536571129Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 3,
                "Log": [
                    {
                        "Start": "2020-10-30T10:08:17.860629438+08:00",
                        "End": "2020-10-30T10:08:17.971073819+08:00",
                        "ExitCode": 1,
                        "Output": "ping failed\n"
                    },
                    {
                        "Start": "2020-10-30T10:08:47.983726282+08:00",
                        "End": "2020-10-30T10:08:48.093252329+08:00",
                        "ExitCode": 1,
                        "Output": "ping failed\n"
                    },
                    {
                        "Start": "2020-10-30T10:09:18.10217741+08:00",
                        "End": "2020-10-30T10:09:18.214696858+08:00",
                        "ExitCode": 1,
                        "Output": "ping failed\n"
                    },
                    {
                        "Start": "2020-10-30T10:09:48.219019542+08:00",
                        "End": "2020-10-30T10:09:48.343633873+08:00",
                        "ExitCode": 1,
                        "Output": "ping failed\n"
                    },
                    {
                        "Start": "2020-10-30T10:10:18.351930986+08:00",
                        "End": "2020-10-30T10:10:18.466557964+08:00",
                        "ExitCode": 1,
                        "Output": "ping failed\n"
                    }
                ]
            }
        },
        ...
}
```

**To Reproduce**
Normally start the container without any persistent store.

**Expected behavior**
Can start the container successfully.

**Host (please complete the following information):**
 - OS: CentOS
 - Version: 7

**Image (please complete the following information):**
 - Tag: alpine
 - Image ID: dc943559fa76

**Comment by WhiteBahamut** [comment]
Quick workaround ist to set the health chack manually in your compose or with docekr run.

**Comment by mko-x** [comment]
For most configurations there is no problem with the healthcheck. The healthcheck is used to determine if the container is somehow working.

We could provide a flag to disable the healthcheck or to set it to another period, can't we?

**Comment by mko-x** [comment]
And puh, thank you @sammyhk  :D

I didn't see the usecase for running this without any persistent volume yet. Would be interesting which hardware and usecase you are on?

> **Describe the bug**
> Container cannot be started if do not have persistent volume due to the change of the start period ([6b837a3#diff-ad6dc7c04f23afe88d0cd808022c0f03b443568ca479de506b38ebb757ff86fcR28](https://github.com/mko-x/docker-clamav/commit/6b837a347deddb8a04d783e02c410f882854fd2e#diff-ad6dc7c04f23afe88d0cd808022c0f03b443568ca479de506b38ebb757ff86fcR28)). It got stopped when clamav still starting up to download newest update.
> `docker logs -f <container id>` got following:
> 
> ```
> [bootstrap] Initial clam DB download.
> Fri Oct 30 02:07:17 2020 -> ClamAV update process started at Fri Oct 30 02:07:17 2020
> Fri Oct 30 02:07:17 2020 -> daily database available for download (remote version: 25972)
> Fri Oct 30 02:08:56 2020 -> Testing database: '/var/lib/clamav/tmp.d8849/clamav-3f5df84d1dffe0dfb95a7563cbe75a43.tmp-daily.cvd' ...
> Fri Oct 30 02:09:12 2020 -> Database test passed.
> Fri Oct 30 02:09:12 2020 -> daily.cvd updated (version: 25972, sigs: 4336908, f-level: 63, builder: raynman)
> Fri Oct 30 02:09:12 2020 -> main database available for download (remote version: 59)
> <at this time, still downloading update, health check fail and container got killed>
> ```
> 
> `docker inspect <container id>` got following:
> 
> ```
> {
>         ...
>         "State": {
>             "Status": "exited",
>             "Running": false,
>             "Paused": false,
>             "Restarting": false,
>             "OOMKilled": false,
>             "Dead": false,
>             "Pid": 0,
>             "ExitCode": 137,
>             "Error": "",
>             "StartedAt": "2020-10-30T02:07:17.656967439Z",
>             "FinishedAt": "2020-10-30T02:10:30.536571129Z",
>             "Health": {
>                 "Status": "unhealthy",
>                 "FailingStreak": 3,
>                 "Log": [
>                     {
>                         "Start": "2020-10-30T10:08:17.860629438+08:00",
>                         "End": "2020-10-30T10:08:17.971073819+08:00",
>                         "ExitCode": 1,
>                         "Output": "ping failed\n"
>                     },
>                     {
>                         "Start": "2020-10-30T10:08:47.983726282+08:00",
>                         "End": "2020-10-30T10:08:48.093252329+08:00",
>                         "ExitCode": 1,
>                         "Output": "ping failed\n"
>                     },
>                     {
>                         "Start": "2020-10-30T10:09:18.10217741+08:00",
>                         "End": "2020-10-30T10:09:18.214696858+08:00",
>                         "ExitCode": 1,
>                         "Output": "ping failed\n"
>                     },
>                     {
>                         "Start": "2020-10-30T10:09:48.219019542+08:00",
>                         "End": "2020-10-30T10:09:48.343633873+08:00",
>                         "ExitCode": 1,
>                         "Output": "ping failed\n"
>                     },
>                     {
>                         "Start": "2020-10-30T10:10:18.351930986+08:00",
>                         "End": "2020-10-30T10:10:18.466557964+08:00",
>                         "ExitCode": 1,
>                         "Output": "ping failed\n"
>                     }
>                 ]
>             }
>         },
>         ...
> }
> ```
> 
> **To Reproduce**
> Normally start the container without any persistent store.
> 
> **Expected behavior**
> Can start the container successfully.
> 
> **Host (please complete the following information):**
> 
>     * OS: CentOS
> 
>     * Version: 7
> 
> 
> **Image (please complete the following information):**
> 
>     * Tag: alpine
> 
>     * Image ID: dc943559fa76

**Comment by sammyhk** [comment]
Checked with command `docker run -d -p 3310:3310 mkodockx/docker-clamav:alpine`, it needs at least 8 minutes to startup. And the container marked `unhealthy` status.
When run with docker swarm mode by the default settings, it will kill and restart the container when it marked as `unhealthy` status, so this issue occurred.

Checked the path `/var/lib/clamav` inside container:
```
~ $ ls -lah
total 261M
drwxr-xr-x    1 clamav   clamav      4.0K Nov  3 08:27 .
drwxr-xr-x    1 root     root        4.0K Oct 28 15:57 ..
-rw-------    1 clamav   clamav       489 Nov  3 08:37 .ash_history
-rw-r--r--    1 clamav   clamav    289.4K Nov  3 08:27 bytecode.cvd
-rw-r--r--    1 clamav   clamav    108.8M Nov  3 08:20 daily.cvd
-rw-r--r--    1 clamav   clamav    112.4M Nov  3 08:27 main.cvd
-rw-r--r--    1 clamav   clamav     39.4M Nov  3 08:27 safebrowsing.cvd
```
I think it is in hard to download ~260MB within 2 minutes, the previous value (i.e. 500s) should be reasonable.
Please note, even I configured to use persistent volume, it cannot be started as the first time initialization always fail.
For this reason, I would recommend to rollback `start-period` to 500s.

**Comment by WhiteBahamut** [comment]
You can change the start period by using `--health-start-period 2m`, see [docker run](https://docs.docker.com/engine/reference/commandline/run/). Never the less I still think the healthcheck should be better be configured from outsite.

**Comment by WhiteBahamut** [comment]
Creating a PR, can someone check the compose command?
