### ISSUE TITLE
clamd.conf renamed to clam.conf in bootstrap.sh prevents clamd starting

### ISSUE THREAD

**Issue by james-airbox** [mko-x/docker-clamav#89]
**Describe the bug**
A rename of the file clamd.conf to clam.conf in the bootstrap.sh file causes deployments to fail with a custom calmd.conf file which is mounted by a mapped volume. 

`[bootstrap] Run clamav daemon...
ERROR: Can't open/parse the config file /etc/clamav/clam.conf
`

clamd.conf was renamed to clam.conf to support custom conf files, part of [this commit](https://github.com/mko-x/docker-clamav/commit/e96e6107b46ddc5feb0dfb5490ffc68fa1252194)

This moves away from the standard name of a clamav config file in documentation elsewhere:
[https://www.clamav.net/documents/configuration#clamdconf](https://www.clamav.net/documents/configuration#clamdconf)
[https://linux.die.net/man/5/clamd.conf](https://linux.die.net/man/5/clamd.conf)

**To Reproduce**
Run the image with a volume mounted and a clamd.conf present

**Expected behavior**
Config is loaded and the clamav daemon is run

**Host (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Docker version 19.03.13, build 4484c46d9d

**Image (please complete the following information):**
 - docker-clamav:alpine
 - Configuration: 
Extract from docker swarm compose file:
```  abx-platform-clamav:
    image: customImageWithEurekaSidecar:2.0.8-SNAPSHOT
    volumes:
      - /home/user/Projects/projectname/backend/platform-clamav/conf/:/etc/clamav
      - /home/user/Projects/projectname/backend/platform-clamav/store/:/store
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '0.25'
          memory: 1024M
    ports:
       - '3310:3310'
       - '3311:3311'
       - '8840:8840'
    hostname: platform-clamav
    networks:
      - project-net 
```

**Additional context**
Not sure if the config file rename was intentional or not. We are quick fixing this by duplicating the clamd.conf and having both clamd.conf and clam.conf in our mapped volume

**Comment by mko-x** [comment]
The problem was, that clamav was started with the explicit conf file path to clamd.conf - so custom conf should not have been used IMHO

```
exec /usr/sbin/clamd -c /etc/clamav/clamd.conf
```

**Comment by DavidJFowler** [comment]
> The problem was, that clamav was started with the explicit conf file path to clamd.conf - so custom conf should not have been used IMHO
> 
> ```
> exec /usr/sbin/clamd -c /etc/clamav/clamd.conf
> ```

Is there a reason why this is only so in the "edge" image? In main (https://github.com/mko-x/docker-clamav/blob/master/alpine/main/bootstrap.sh) it reads
```
exec /usr/sbin/clamd -c /etc/clamav/clam.conf
```
