### ISSUE TITLE
Not running in daemon mode?

### ISSUE THREAD

**Issue by KenJusticeJr** [mko-x/docker-clamav#9]
I am running this docker container along side a Nextcloud installation, and running the Nextcloud antivirus app in daemon mode to connect to ClamAV. I am getting the following error in the Nextcloud logs:
`
Error | files_antivirus | OCA\Files_Antivirus\BackgroundJob\BackgroundScanner::run, exception: The clamav module is not configured for daemon mode.
`
Any idea where I should begin looking? Thank you!

**Comment by mko-x** [comment]
I will investigate that point. Didn't run the container with Nextcloud very often yet. Could you please provide information about your Nextcloud container and its configuration?

**Comment by KenJusticeJr** [comment]
Here is my docker-compose.yml file:
`
version: '2'

services:
  db:
    container_name: db
    build: ./db
    restart: always
    volumes:
      - /mnt/nextcloud/db:/var/lib/mysql
    env_file:
      - ./env/db.env

  redis:
    container_name: redis
    image: redis
    restart: always

  app:
    container_name: app
    build: ./app
    restart: always
    volumes:
      - /mnt/nextcloud/html:/var/www/html
      - /mnt/nextcloud/html/apps:/var/www/html/apps
      - /mnt/nextcloud/html/custom_apps:/var/www/html/custom_apps
      - /mnt/nextcloud/html/assets:/var/www/html/assets
      - /mnt/nextcloud/html/config:/var/www/html/config
      - /mnt/nextcloud/html/data:/var/www/html/data
      - /mnt/nextcloud/html/themes:/var/www/html/themes
    environment:
      - MYSQL_HOST=db
    env_file:
      - ./env/app.env
    networks:
      - proxy-tier
      - default
      - av-net
    depends_on:
      - db
      - redis

  office:
    container_name: office
    image: collabora/code
    env_file:
      - ./env/office.env
    cap_add:
      - MKNOD
    expose:
      - 9980
    restart: always
    volumes:
      - /mnt/nextcloud/office/conf.d:/etc/httpd/conf.d
    networks:
      - proxy-tier
    depends_on:
      - app

  cron:
    container_name: cron
    build: ./app
    restart: always
    volumes:
      - /mnt/nextcloud/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    container_name: proxy
    build: ./proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /mnt/proxy/certs:/etc/nginx/certs:ro
      - /mnt/proxy/vhost.d:/etc/nginx/vhost.d
      - /mnt/proxy/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /mnt/proxy/certs:/etc/nginx/certs
      - /mnt/proxy/vhost.d:/etc/nginx/vhost.d
      - /mnt/proxy/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

  antivirus:
    container_name: antivirus
    image: mkodockx/docker-clamav
    restart: always
    expose:
      - 3310
    networks:
      - av-net

networks:
  proxy-tier:
  av-net:
`

**Comment by KenJusticeJr** [comment]
Here are the settings inside NextCloud:
![antivirusconfig](https://user-images.githubusercontent.com/7537761/39317680-3060adf8-494a-11e8-9ad7-0580f19dba60.png)

**Comment by mko-x** [comment]
Can you reach the antivirus container from within your app via bash?

The error message is regarding to wrong nextcloud configuration. Try asking somebody within that community.

I know the section for owncloud is working:
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/antivirus_configuration.html

**Comment by KenJusticeJr** [comment]
Yes, it is reachable.

Ok, I'll work in that community. Thanks.

**Comment by xthursdayx** [comment]
Hey @KenJusticeJr did you ever get this figured out? I'm having the exact same problem. Thanks.

**Comment by mko-x** [comment]
The clamav is configured to run in foreground otherwise the container would die. But clamd and freshclamd stay daemons.

Regarding @KenJusticeJr - as I see your config today, you are missing linkage and depends_on from the nextcloud app to the clamav. Networking should be enough but missing depends_on could activate some kind race condition.

Hey @xthursdayx  if you provide your config here or via pn, I would take look. I gonna update docs here.
