### ISSUE TITLE
Consistent environment variables identifier

### ISSUE THREAD

**Issue by mko-x** [mko-x/docker-clamav#90]
At the Moment there are five environment variables used:

* HTTPProxyServer
* HTTPProxyPort
* DatabaseMirror
* FRESHCLAM_CONF_FILE
* CLAMD_CONF_FILE

The last both should be camel-case like the first or other way round.

**Comment by WhiteBahamut** [comment]
agreed, I usually look at the alpine image. Saying that, I am not sure if the first three are even present within the alpine images oO
