### ISSUE TITLE
Unable to set clamd.conf via environment variables

### ISSUE THREAD

**Issue by jchum-work** [mko-x/docker-clamav#94]
**Describe the bug**

All bootstrap files use FRESHCLAM_CONF_FILE instead of CLAMD_CONF_FILE to source the clamd.conf file.

**Expected behavior**

Use CLAMD_CONF_FILE  variable to set clamd.conf.

Files:
* https://github.com/mko-x/docker-clamav/blob/1d7b0b5536f63cb8f2427212f567a9835f5c1bc7/alpine/main/bootstrap.sh#L13
* https://github.com/mko-x/docker-clamav/blob/1d7b0b5536f63cb8f2427212f567a9835f5c1bc7/debian/stretch/bootstrap.sh#L15
* etc...

**Comment by mko-x** [comment]
Fixed by #95 
Thanks to @ericmason

**Comment by jchum-work** [comment]
Thanks!
