### ISSUE TITLE
envconfig.sh is creating an invalid clamd.conf file

### ISSUE THREAD

**Issue by OG84** [mko-x/docker-clamav#99]
When using the `debian buster slim` image and providing the environment variable `CLAMD_CONF_FILE`, container will error with `Cannot parse file, Unknown option FILE`
Which makes sense, because in `envconfig.sh`, looks like we're appending those vars to the clamd.conf.

```
for OUTPUT in $(env | awk -F "=" '{print $1}' | grep "^CLAMD_CONF_"); do
    TRIMMED="${OUTPUT/CLAMD_CONF_/}"
    grep -q "^$TRIMMED " /etc/clamav/clamd.conf && sed "s/^$TRIMMED .*/$TRIMMED ${!OUTPUT}/" -i /etc/clamav/clamd.conf ||
        sed "$ a\\$TRIMMED ${!OUTPUT}" -i /etc/clamav/clamd.conf
done
```

So if we set an env var `CLAMD_CONF_FILE=/path/to/conf`, the clamd.conf file will get an option like
```
FILE /path/to/conf
...
```
Which leads to a parsing error.

I think this is the related PR which introduced the bug -> https://github.com/mko-x/docker-clamav/pull/31

**Comment by mko-x** [comment]
Do you have a recommendation?

**Comment by OG84** [comment]
yeah maybe exclude CLAMD_CONF_FILE from the above script, so that we dont use FILE as a property name.
e.g. https://stackoverflow.com/questions/4538253/how-can-i-exclude-one-word-with-grep


Something like (not tested).

`for OUTPUT in $(env | awk -F "=" '{print $1}' | grep -v "^CLAMD_CONF_FILE" | grep "^CLAMD_CONF_"); do`

**Comment by olivier1980** [comment]
I have this issue as well
